In [ ]:
import tensorflow as tf
from tensorflow import keras
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'


fashion_mnist_data = keras.datasets.fashion_mnist
(all_x_train, all_y_train), (x_test, y_test) = fashion_mnist_data.load_data()

all_x_train = all_x_train.astype('float32')
x_test = x_test.astype('float32')



In [ ]:

x_validation, x_train = all_x_train[:5000] / 255.0, all_x_train[5000:] / 255.0
y_validation, y_train = all_y_train[:5000], all_y_train[5000:]



fashion_mnist_class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat", "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]




In [ ]:
model = keras.models.Sequential()

model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(300, activation="relu"))

my_weights_initializer = tf.keras.initializers.RandomNormal(mean=100., stddev=1.)
my_bias_initializer= tf.keras.initializers.Ones()
model.add(keras.layers.Dense(150, activation="relu" ,\
                                  kernel_initializer = my_weights_initializer, \
                                  bias_initializer = my_bias_initializer))
# model.add(keras.layers.Dense(150, activation="relu"))

model.add(keras.layers.Dense(10,activation="softmax"))

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_6 (Dense)             (None, 300)               235500    
                                                                 
 dense_7 (Dense)             (None, 150)               45150     
                                                                 
 dense_8 (Dense)             (None, 10)                1510      
                                                                 
Total params: 282160 (1.08 MB)
Trainable params: 282160 (1.08 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
print(model.layers)







[<keras.src.layers.reshaping.flatten.Flatten object at 0x7eeed45abe80>, <keras.src.layers.core.dense.Dense object at 0x7eeed45f8340>, <keras.src.layers.core.dense.Dense object at 0x7eeed45f9f60>, <keras.src.layers.core.dense.Dense object at 0x7eeed45aa6e0>]


In [ ]:
print(model.layers[2].name)


dense_7


In [ ]:
import torch

In [ ]:
tens =  torch.arange(1,7)
print(tens)

tensor([1, 2, 3, 4, 5, 6])


In [ ]:
tens_np = np.array(tens)
print(tens_np)

[1 2 3 4 5 6]


In [ ]:
tens.view(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
transformed = tens.view(2,3)
transformed.sum(dim=0)

tensor([5, 7, 9])

In [ ]:
transformed.sum(dim=1)

tensor([ 6, 15])

In [ ]:
transformed[1,1] = 10
transformed

tensor([[ 1,  2,  3],
        [ 4, 10,  6]])

In [ ]:
x = torch.randn(2,2, requires_grad=True)
x

tensor([[-0.1539,  1.0827],
        [-0.3543,  1.4096]], requires_grad=True)

In [ ]:
print(x, x.dtype, x.shape)

tensor([[-0.1539,  1.0827],
        [-0.3543,  1.4096]], requires_grad=True) torch.float32 torch.Size([2, 2])


In [ ]:
out = x.pow(2).sum()

In [ ]:
out.backward()

In [ ]:
print(x.grad)
print(2*x)

tensor([[-0.3079,  2.1655],
        [-0.7086,  2.8192]])
tensor([[-0.3079,  2.1655],
        [-0.7086,  2.8192]], grad_fn=<MulBackward0>)


In [ ]:
ST1 = np.array([[17.0,12,13,15,15,20,20], [10,12,14,15,20,15,20]])
ST2 = np.array([4,7.5,10,11,5,5,6,8,5,0,5,0,10,6]).reshape(2,7)

In [ ]:
print(ST2)

[[ 4.   7.5 10.  11.   5.   5.   6. ]
 [ 8.   5.   0.   5.   0.  10.   6. ]]


In [ ]:
Xstudents= np.concatenate((ST1,ST2), axis=1)

In [ ]:
Ystudents = np.ones(14)
Ystudents[7:] = 0

In [ ]:
print(Ystudents)

[1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
X = torch.FloatTensor(Xstudents.T)
Y = torch.FloatTensor(Ystudents)

In [ ]:
print(f'Diemension de y: {Y.shape}')

Diemension de y: torch.Size([14])


In [ ]:
print(f'Diemension de X {X.shape}')

Diemension de X torch.Size([14, 2])


In [ ]:
D_in = 2
D_out = 1

In [ ]:
model = torch.nn.Sequential(
    torch.nn.Linear(D_in,D_out),
    torch.nn.Sigmoid()
)

In [ ]:
print(model)

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)


In [ ]:
loss_fn = torch.nn.BCELoss()
learning_rate = 1e-2
optimize = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [ ]:
prediction = model(X[0])

In [ ]:
print(prediction)

tensor([0.1038], grad_fn=<SigmoidBackward0>)


In [ ]:
prediction = model(X[0:3])

In [ ]:
print(prediction)

tensor([[0.1038],
        [0.6570],
        [0.7544]], grad_fn=<SigmoidBackward0>)


In [ ]:
prediction = model(X)
print(prediction)

tensor([[0.1038],
        [0.6570],
        [0.7544],
        [0.6846],
        [0.9492],
        [0.2369],
        [0.7277],
        [0.8848],
        [0.3511],
        [0.0232],
        [0.1218],
        [0.1425],
        [0.9249],
        [0.5987]], grad_fn=<SigmoidBackward0>)


In [ ]:
Ymodified = Y.view(-1,1)

In [ ]:
print(f"La premiere predicition: {prediction}, {prediction.shape}")

La premiere predicition: tensor([[0.1038],
        [0.6570],
        [0.7544],
        [0.6846],
        [0.9492],
        [0.2369],
        [0.7277],
        [0.8848],
        [0.3511],
        [0.0232],
        [0.1218],
        [0.1425],
        [0.9249],
        [0.5987]], grad_fn=<SigmoidBackward0>), torch.Size([14, 1])


In [ ]:
print(f'le label: {Ymodified[0]}, {Ymodified[0].shape}')

le label: tensor([1.]), torch.Size([1])


In [ ]:
prediction = model(X[0])

In [ ]:
print(f'La valeur de la loss: , {loss_fn(prediction,Ymodified[0])}')

La valeur de la loss: , 2.265641927719116


In [ ]:
A = torch.from_numpy(np.array([[2.,3.],[1.,0.]]))
A.requires_grad = True

B = torch.from_numpy(np.array([[1.,2.], [3.,4.]]))
B.requires_grad = True

C = torch.matmul(A, B)

d = torch.from_numpy(np.array([[3.], [2.]]))
d.requires_grad = True

E = C + d

J = torch.sum(E)

In [ ]:
C

tensor([[11., 16.],
        [ 1.,  2.]], dtype=torch.float64, grad_fn=<MmBackward0>)

In [ ]:
  E

tensor([[14., 19.],
        [ 3.,  4.]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [ ]:
J.backward()

In [ ]:
d.grad

tensor([[2.],
        [2.]], dtype=torch.float64)

In [ ]:
print(A.grad)


tensor([[3., 7.],
        [3., 7.]], dtype=torch.float64)


In [ ]:
B.grad

tensor([[3., 3.],
        [3., 3.]], dtype=torch.float64)

In [ ]:
# Réinitialiser les gradients
A.grad = None
B.grad = None
d.grad = None

# Rétropropagation pour calculer les gradients
J.backward()

# Afficher les gradients par rapport à A
print(A.grad)


RuntimeError: ignored

In [ ]:
Z = torch.from_numpy(np.array([[1.,2.], [3.,4.]]))
Z.requires_grad = True
X = torch.from_numpy(np.array([[3.,2.], [4.,2.]]))
X.requires_grad = True

v = torch.from_numpy(np.array([[0.,1.], [2.,1.]]))
v.requires_grad = True
Y = torch.matmul(Z, X)

U = v+Y

H = torch.sum(U)

In [ ]:
print(Z.grad)

tensor([[5., 6.],
        [5., 6.]], dtype=torch.float64)


In [ ]:
H.backward()

In [ ]:
x1 = torch.tensor(10., requires_grad=True)
x2 = torch.tensor(20., requires_grad=True)
x3 = x1*x2

x3.backward()
print(x1.grad)
print(x2.grad)

tensor(20.)
tensor(10.)
